### ISSUE TITLE
osThreadNew() called with priority == osPriorityNone

### ISSUE THREAD

**Issue by MichaelMleczko** [ARM-software/CMSIS-RTOS2_Validation#36]
The validation suite does not set the priority in `tf_main_attr`. Thus the thread is created with `osPriorityNone = 0, ///< No priority (not initialized).`.

How shall osThreadNew() handle this?

Should the priority then be set to osPriorityNormal within osThreadNew(), or should it return NULL?

And is this a mistake in the validation suite and it should provide a valid priority?

And what if the priority would be set to osPriorityIdle, since this priority is "Reserved for Idle thread" according to cmsis_os2.h?

**Comment by VladimirUmek** [comment]
Hi,

any uninitialized members shall be set to their default values, see [osThreadAttr_t documentation](https://www.keil.com/pack/doc/CMSIS/RTOS2/html/group__CMSIS__RTOS__ThreadMgmt.html#structosThreadAttr__t).
Therefore in case of osThreadAttr_t.priority the value set shall be osPriorityNormal.

Regarding tf_main_attr I agree, that settings should be more specific and should not rely only on defaults. In addition at least member .priority will be specified and set to osPriorityNormal, since validation project expects/assumes that TestRunner runs as osPriorityNormal.

Thanks for raising this!

**Comment by VladimirUmek** [comment]
The issue was addressed, hence closing it.
