### ISSUE TITLE
Spurious failure of TC_osMessageQueuePut_2

### ISSUE THREAD

**Issue by andyturk** [ARM-software/CMSIS-RTOS2_Validation#48]
I've been running the validation suite against a V5.5.0 version of CMSIS-RTOS RTX. All but one of the test cases pass. The one that fails is `TC_osMessageQueuePut_2`.

Specifically, this assert (in the corresponding ISR) fails:

https://github.com/ARM-software/CMSIS-RTOS2_Validation/blob/5c27a1f0851e7f7627347753471429037bc3da33/Source/RV2_MessageQueue.c#L352

The test case essentially fills up a message queue while executing an ISR and then verifies the messages in threaded code. The assert above is part of the ISR and executes in an interrupt context.

I've single-stepped the kernel in my implementation and found that `osMessageQueueGetSpace()` really is returning non-zero even though the queue was just filled to capacity immediately before.

The issue is that `osMessageQueueGetSpace()` basically boils down to `.max_blocks - .msg_count`, and the `.msg_count` field of the message queue isn't actually updated until after the ISR returns. I.e., the blocks are "used" but not yet "counted" at the time of the assert in the test code.

If I comment out the assertion and run the modified test suite, everything passes. The `.msg_count` field of the message queue does get updated, but that happens in the PendSV handler just before returning to a thread context.

Or maybe this is a bug in the kernel? The documentation for `osMessageQueueGetSpace()` says the function can be called from within an ISR but the implementation returns a value that probably isn't useful.

**Comment by VladimirUmek** [comment]
Hi,
this issue is known and your investigation is correct. We reviewed the code again and will investigate for potential solution.

This test case is written in a way to show this kind of issues and I'm unsure if you had issues in a real world application. Although the function is not working correctly when called from ISR, most likely this does not represent a problem in a well written real world application, where you would usually call osMessageQueueGetSpace before putting a message into the message queue. Nevertheless, the functionality is not as specified by the API and we will look into this.

**Comment by andyturk** [comment]
Thanks, Vladimir. You're right, we don't have any application problem with how message queues are implemented.

Having a non-passing test case is a slight irritation, but that's all.

**Comment by RobertRostohar** [comment]
The following patch should fix the RTX implementation to return the correct value also from ISR:
https://github.com/ARM-software/CMSIS-RTX/commit/8f719e57f6100b24ec78e476576133195b7ed38b

**Comment by VladimirUmek** [comment]
The issue should now be resolved:
- RTX5 implementation was reviewed and fixed
- test cases were reviewed and changed to test a more real-world ISR processing scenario
